# Generated by Django 4.1.7 on 2023-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0004_post_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='verify_post',
            name='bid_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
